version: '2'

services:
  discord-netcore:
    image: discord-netcore:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
